# Site settings
title: Scrapy - A Fast and Powerful Scraping and Web Crawling Framework
url: "http://scrapy.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: pygments
encoding: utf-8