# Site settings
title: Scrapy - A Fast and Powerful Scraping and Web Crawling Framework
# url: "http://scrapy.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: pygments
encoding: utf-8

navigation:
- text: Download
  url: /download.html
- text: Documentation
  url: /documentation.html
- text: Community
  url: /community.html
- text: Companies
  url: /companies.html
- text: Commercial Support
  url: /support.html